language:       c
script:         make
compiler:       clang
sudo:           true
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libncurses5-dev

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "SIdpf3vgFTJacQzlKmnwbnBSswV3k5HHWf2bjOG2UKx2gGm1oNvl92Tqque56982bY11160poAWBJDf+0CJsfLr4zoSVDuBRsjCdZecol5f/Tb6R/JVZpuFtIplC283mu0JA/GD5XO2G1gJOKId63o+6/20hLNWD+T6bUTVpTV0="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "ajpaulson/srogue11"
      description: "Build Submitted via travis.ci"
    notification_email: whileforkdofork@gmail.com
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan

branches:
  only:
    - master
    - coverity_scan
notifications:
  email:
    - whileforkdofork@gmail.com
  webhooks:
    urls:
      https://webhooks.gitter.im/e/bb93f45f48ed089b8407
    on_success: change
    on_failure: always
    on_start: never
