language:       c
script:         make
compiler:       clang
sudo:           true
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libncurses5-dev
notifications:
  email:
    - whileforkdofork@gmail.com
